---
- name: Install Ruby dependences packages
  yum:
    name: "{{ dependences }}"
  vars:
    dependences:
      - gcc-c++
      - glibc-headers
      - openssl-devel
      - readline
      - libyaml-devel 
      - readline-devel 
      - zlib 
      - zlib-devel 
      - libffi-devel 
      - libxml2 
      - libxslt 
      - libxml2-devel
      - libxslt-devel 
      - sqlite-devel

- name: Install rbenv
  git:
    repo: "{{ rbenv_download_url }}"
    dest: /usr/local/rbenv

- name: Edit bashrc
  template:
    src: roles/ruby/templates/rbenv_system.sh.j2
    dest: /etc/profile.d/rbenv.sh
    owner: ec2-user
    group: ec2-user

- name: Install ruby-build
  git:
    repo: "{{ ruby_build_download_url }}"
    dest: /usr/local/rbenv/plugins/ruby-build

- name: Install ruby
  shell: bash -lc "rbenv install -s {{ ruby_version }}"

- name: Set global ruby version
  shell: bash -lc "rbenv global {{ ruby_version }} && rbenv rehash"
